---
################################################################
###
##   Role description: 
##     The main objective for this role is to install the smartmontools package and 
##     copy the checkmk smartmonitor plugin to the checkmk agent plugin directory.
##
##   Author: Daniel Sol
###
#################################################################


# include when RHEL
- name: Include RHEL-specific tasks
  include_tasks: rhel.yml
  when: 
    - ansible_os_family == "RedHat" or ansible_os_family == "CentOS"

# include when Debian
- name: Include Debian-specific tasks
  include_tasks: debian.yml
  when: 
    - ansible_os_family == "Debian"

# include when Ubuntu
- name: Include Ubuntu-specific tasks
  include_tasks: ubuntu.yml
  when: 
    - ansible_os_family == "Ubuntu"
